### PR TITLE
add Servers.cs, ktexlib_wrap.dll(x64) for dealing .tex file

### PR DESCRIPTION
**Pull request by Akarinnnnn**
### Just pick some code you want.

ktexlibwrap.KTEX.GetRGBA() returns an array, sorted by {r0, g0, b0, a0, r1, g1, b1, a1, ... , rn, gn, bn, an}

Get ktex information (like width, height, encoding) by ktexlibwrap.KTEX.GetInfo()

[ktexlib](https://github.com/Akarinnnnn/MyKleiTools/tree/master/ktexlib) can also compile as a x86 static link library

Servers.cs needs server binary path to start a server(This don't starting server through steam)

### CODE REVIEW

**Comment by Bizarrus** [comment]
Thats nice, i will check the KTEX-Tools when i start to implement the document/editor handlers!

> Servers.cs needs server binary path to start a server(This don't starting server through steam)

Already implemented on 7426f9c88b5659eda8957839a6e39e93403bc522 - See the `DSTC` (C = Client), `DSTT` (T = Tools) and `DSTS` (S = Server) classes. These classes are extended from `KleiGame`.

Before you start to change some thinks, it's better when we discuss about the development. It's a little bit bad, when we sit on the same functions with different code. You must update your repository to prevent override old changes.

**Comment by Akarinnnnn** [comment]
resolved. by the way, is it needed to start server with some arguments like "-cluster DSTEd_test"?

**Comment by Bizarrus** [comment]
its better, when the start its parameterized - here we have a better handling and can implement some nice features such as ServerManager with editing Caves and others..

By the way: the executement must be sandboxed or wrapped to catch their logs or error states

**Comment by Akarinnnnn** [comment]
I knew a way to capture servers' and client's console output: [ReadFile()](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-readfile) function(Native WinAPI) , but it needs a stdout handle, which specified at creating a process by [CreateProcess()](https://docs.microsoft.com/en-us/windows/desktop/api/processthreadsapi/nf-processthreadsapi-createprocessw) function(Also Native WinAPI).

**Comment by Akarinnnnn** [comment]
Found a Lua 5.3 module [KeraLua](https://www.nuget.org/packages/KeraLua)
DST uses Lua 5.3

**Pull request closed without merging**
